#!/usr/bin/env python
# _*_ coding: utf-8 _*_

import time

"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def gen_fib(max_num):
    """
    >>> [v for v in gen_fib(5)]
    [1, 2, 3]
    >>> [v for v in gen_fib(13)]
    [1, 2, 3, 5, 8]
    """
    a, b = 1, 1
    while b < max_num:
        yield b
        a, b = b, a + b

start = time.time()

result = 0
for i in gen_fib(4000000):
    if i % 2 == 0:
        result += i

end = time.time() - start
print result, 'time: ', end
